uploads = []
generated = []

[[outputs]]
id = "3KiTWMRQP70cRhM4e7vUn"
uri = "file://artifacts/resoch-digitals/public/images/about.jpg"
type = "image"
title = "creative team brainstorming agency"

[[outputs]]
id = "SvItF_qiv00UTaJsqU1me"
uri = "file://artifacts/resoch-digitals/public/images/client-1.jpg"
type = "image"
title = "modern restaurant food delivery"

[[outputs]]
id = "m7gBu43_x3wJ3yot1KivV"
uri = "file://artifacts/resoch-digitals/public/images/client-2.jpg"
type = "image"
title = "premium furniture interior design"

[[outputs]]
id = "zl3o6OKvMI4KaHBdMtwfO"
uri = "file://artifacts/resoch-digitals/public/images/client-3.jpg"
type = "image"
title = "luxury real estate architecture"

[[outputs]]
id = "DEN5-HUrPVNkoIl5hm7Cn"
uri = "file://artifacts/resoch-digitals/public/images/client-4.jpg"
type = "image"
title = "professional sound lighting event"

[[outputs]]
id = "go8xXeUMnP_i-7qQiTU8o"
uri = "file://artifacts/resoch-digitals/public/images/client-5.jpg"
type = "image"
title = "architectural design project"

[[outputs]]
id = "iIYEAj5YQ-jiAmTihGnqC"
uri = "file://artifacts/resoch-digitals/public/images/client-6.jpg"
type = "image"
title = "cosmetics beauty product luxury"

[[outputs]]
id = "wN-Q6MmDRgPw4Fyw23BFa"
uri = "file://artifacts/resoch-digitals/public/images/hero-bg.jpg"
type = "image"
title = "abstract digital marketing creative agency"
